name: Update Meme RSS Feed

on:
  workflow_dispatch:      # manual trigger
  schedule:
    - cron: '0 */4 * * *' # every 4 hours

jobs:
  build-rss:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build RSS feed
        shell: bash
        run: python3 scripts/update_feed.py > feed.xml

      - name: Commit & push RSS
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'chore: fix build step to call script'
          file_pattern: 'feed.xml'
