name: Update Meme RSS Feed

on:
  schedule:
    - cron: "0 */4 * * *"
  push:
    branches:
      - main
  workflow_run:
    workflows:
      - "Post Meme to Facebook"
    types:
      - completed

jobs:
  build-rss:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Build RSS feed
        run: python3 scripts/update_feed.py

      - name: Commit & push RSS
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "chore: schedule RSS update every 4h"
          file_pattern: feed.xml
