name: Update Meme RSS Feed

on:
  # Regenerate feed every 4 hours (at minute 0 UTC)
  schedule:
    - cron: '0 */4 * * *'
  # Also whenever main is pushed or your FB workflow finishes
  push:
    branches: [ main ]
  workflow_run:
    workflows: [ "Post Meme to Facebook" ]
    types:     [ completed ]

jobs:
  build-rss:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Build RSS feed
        shell: bash
        run: |
          python3 - << 'PYCODE'
import glob, os, time
from xml.sax.saxutils import escape

items = []
for img in sorted(glob.glob("memes/*.jpg"))[-7:]:
    date = os.path.basename(img).split(".")[0]
    url  = f"https://raw.githubusercontent.com/Carnage1984/auto-90s-memes/main/{img}"
    items.append(f"""
  <item>
    <title>90s Meme for {escape(date)}</title>
    <link>{escape(url)}</link>
    <pubDate>{time.strftime('%a, %d %b %Y %H:%M:%S +0000', time.gmtime())}</pubDate>
  </item>""")

feed = f"""<?xml version="1.0" encoding="UTF-8"?>
<rss version="2.0"><channel>
  <title>Epoch Nostalgia 90s Memes</title>
  <link>https://github.com/Carnage1984/auto-90s-memes</link>
  <description>Daily 90s meme throwback</description>
  {''.join(items)}
</channel></rss>"""

with open("feed.xml", "w") as f:
    f.write(feed)
PYCODE

      - name: Commit & push RSS
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: chore: schedule RSS update every 4h
          file_pattern: feed.xml
