name: Update Meme RSS Feed

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */4 * * *'

permissions:
  contents: write

jobs:
  build-rss:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build RSS feed
        run: python3 scripts/update_feed.py > feed.xml

      - name: Commit & push RSS
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'chore: update RSS feed'
          file_pattern:   'feed.xml'
